version: '3'

services:
  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-helpo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build: helpo-api/.
    restart: always
    env_file:
      - helpo-api/.env
    expose:
      - "8000"
    volumes:
      - ./logs/django:/code/logs
    depends_on:
      - db
  web:
    image: helpo/helpo_web:staging
    restart: always
    env_file:
      - helpo-web/.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./certs:/certs
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - db
      - api
  pgadmin:
    image: fenglc/pgadmin4:alpine
    restart: always
    env_file:
      - ./pgadmin.env
    expose:
      - "5050"
    depends_on:
      - db

# Meant to be used alone, made for pulling from aws
# docker-compose -f docker-compose.local-base.aws.yml COMMAND